version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push docker image
          command: |
            image_name=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
            docker build -t ${image_name} .
            docker tag ${image_name} registry.plyo.website/${image_name}
            docker login -u $PLYO_DOCKER_USER -p $PLYO_DOCKER_PASS https://registry.plyo.website
            docker push registry.plyo.website/${image_name}
      - run:
          name: Post message about deployment into slack
          command: |
            slack_payload='{"channel":"builds","username":"Deployer","icon_emoji":"robot_face","text":"Tag https://github.com/'${CIRCLE_PROJECT_USERNAME}'/'${CIRCLE_PROJECT_REPONAME}'/releases/tag/'${CIRCLE_TAG}' pushed to docker registry and ready for deploy"}'
            curl -X POST --data "payload=${slack_payload}" ${SLACK_WEBHOOK_URL}

workflows:
  version: 2
  publish_to_registry:
    jobs:
      - publish:
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /.*/

